# name of the software
name: Minio Docs
# current version of the software
version: 1.1.0
# url of the download button
downloadUrl: https://github.com/minio/docs
 
# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url:  https://github.com/minio/docs

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url:  https://github.com/minio/docs
  - title: Issues
    url:  https://github.com/minio/docs
# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: minio
  repo: docs

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile', 'gulpfile.js', 'node_modules', 'package.json', 'less']

markdown: rdiscount

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

# SDK
sdk:
  - title: Golang
    class: golang
  - title: Node.js
    class: nodejs
  - title: Ruby
    class: ruby
  - title: Python
    class: python
  - title: Java
    class: java
  - title: .Net
    class: net

#documentation links
docLinks:
  - title : Minio Server
    url   : #
  - title : Minio Client
    url   : #
  - title : Minio SDK Golang
    url   : #
  - title : Minio SDK Node.js
    url   : #
  - title : Minio SDK Ruby
    url   : #
  - title : Minio SDK Python
    url   : #
  - title : Minio SDK Java
    url   : #
  - title : Minio SDK .Net
    url   : #

# SDK sub links
sdkLinks: ['Quick Start Guide', 'API', 'Recipes', 'Examples', 'Best Practise']
